### ISSUE TITLE
Differences in behaviour between IOS and Android

### ISSUE THREAD

**Issue by LukasSonnabend** [douglasjunior/react-native-applifecycle#4]
I need to run a function incase the user leaves the app, this is working perfectly on iOS as leaving the app triggers the "background" state and going back to the app triggers active. In Android the behaviour is as such: 
- Leaving the App -> No Event
- Returning to the App: Background and Active States are running in direct succession.

Incase this is expected I am sorry for wasting your time.

Info:

- How did you link to the library (autolinking, manual, rn link, cocoapods)?
-  autolinking
- What version of React Native?
-  0.71.8
-  What version of the library?
-  0.4.0/1.0.0
-  iOS/Android version?
-  Android
- Did the problem happen after updating React Native?
- no
- Are you using the library for the first time?
- yes
- It's a bug? Provide a link to a minimal reproduction case.
- Unsure? Maybe its expected behaviour

**Comment by douglasjunior** [comment]
Have you tried with the react-native `AppState` on Android? The behavior is the same?

**Comment by douglasjunior** [comment]
Have just tested in the [Sample](https://github.com/douglasjunior/react-native-applifecycle/blob/main/Sample/App.tsx) project and the behaviors were as expected.

When goes to background:

![Screenshot 2024-08-07 at 10 42 34](https://github.com/user-attachments/assets/c9e724f2-fe70-4f2b-ac86-9fedd0a75bc2)

When becomes active again:

![Screenshot 2024-08-07 at 10 42 45](https://github.com/user-attachments/assets/d5462dda-fe4f-4028-80f4-9f191b45d9dc)
