### ISSUE TITLE
[Question] Can this library helps with native password manager?

### ISSUE THREAD

**Issue by anniewey** [douglasjunior/react-native-applifecycle#9]
Hi, for the context I'm building a lock screen that will show whenever user leave the app and return. For this handling, I've use `AppState` to listen to the changes. 

But I'm encountering problem when my user is trying to fill in password field in the app by using his ios password manager. Whenever my user open his password manager, the appstate listener was triggered and causing the lock screen to show. I supposed it was cause of the app go out of focus when the password manager is open. The lock screen shouldn't be shown in this case where user trying to fill his password in the app. 

I have tried to remove `inactive` from checking but not helping either. Is there any workaround for this? Or can this library helps?

```
useEffect(() => {
    function onAppStateChange(nextState: AppStateStatus) {
      if (appState.current?.match(/background/) && nextState === 'active') {
        handlePinCheck(); //show lock screen
      } else {
        AppSettings.updateLastActive(Date.now());
      }
      appState.current = nextState;
    }

    const appStateListener = AppState.addEventListener(
      'change',
      onAppStateChange,
    );

    return () => {
      appStateListener.remove();
    };
  }, [handlePinCheck]);
```

**Comment by douglasjunior** [comment]
This is a good question, I have never used the iOS password manager.

Can you help me with some step by step on how to reproduce this?

**Comment by anniewey** [comment]
@douglasjunior my bad for not double checking, it's actually working after removing the `inactive` state. my user reported wrongly. sorry for the trouble. thanks anw!
